ERROR - 2023-10-16 00:10:38 --> ErrorException: pg_query(): Query failed: ERROR:  syntax error at or near ","
LINE 3:  "price" varchar(10,2) NOT NULL,
                           ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'CREATE TABLE "s...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "s...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "s...')
#4 C:\teste_api_codeigniter\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "s...')
#5 C:\teste_api_codeigniter\app\Database\Migrations\2023-10-15-230635_Sales.php(46): CodeIgniter\Database\Forge->createTable('sales', true)
#6 C:\teste_api_codeigniter\system\Database\MigrationRunner.php(877): App\Database\Migrations\Sales->up()
#7 C:\teste_api_codeigniter\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\teste_api_codeigniter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\teste_api_codeigniter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\teste_api_codeigniter\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\teste_api_codeigniter\spark(102): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-10-16 01:21:46 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ..., &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('800', '1', 'Pago', '2...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 01:21:46 --> pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ..., &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('800', '1', 'Pago', '2...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 01:22:19 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ...created_at&quot;, &quot;updated_at&quot;) VALUES ('800.00', '1', 'Pago', '2...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 01:22:19 --> pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ...created_at&quot;, &quot;updated_at&quot;) VALUES ('800.00', '1', 'Pago', '2...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 01:33:15 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ...created_at&quot;, &quot;updated_at&quot;) VALUES ('800.00', '1', 'Pago', '2...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 01:33:15 --> pg_query(): Query failed: ERROR:  invalid input syntax for type integer: &quot;Pago&quot;
LINE 1: ...created_at&quot;, &quot;updated_at&quot;) VALUES ('800.00', '1', 'Pago', '2...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 01:34:01 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (1, 800.00, 1, null, Pago, 2023-10-16 01:34:01, 2023-10-16 01:34:01). in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 01:34:01 --> pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (1, 800.00, 1, null, Pago, 2023-10-16 01:34:01, 2023-10-16 01:34:01).
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 01:39:28 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (2, 800.00, 1, null, Pago, 2023-10-16 01:39:26, 2023-10-16 01:39:26). in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 01:39:28 --> pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (2, 800.00, 1, null, Pago, 2023-10-16 01:39:26, 2023-10-16 01:39:26).
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 11:56:53 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (3, 800.00, 1, null, Pago, 2023-10-16 11:56:53, 2023-10-16 11:56:53). in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(31): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 11:56:53 --> pg_query(): Query failed: ERROR:  null value in column &quot;products_id&quot; of relation &quot;sales&quot; violates not-null constraint
DETAIL:  Failing row contains (3, 800.00, 1, null, Pago, 2023-10-16 11:56:53, 2023-10-16 11:56:53).
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-16 12:17:28 --> Undefined array key "name"
in APPPATH\Controllers\Sale.php on line 44.
 1 APPPATH\Controllers\Sale.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\teste_api_codeigniter\\app\\Controllers\\Sale.php', 44)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->update('4')
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-16 14:04:38 --> "O campo :name é obrigatório" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 317.
 1 SYSTEMPATH\Validation\Validation.php(317): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('O campo :name é obrigatório')
 2 SYSTEMPATH\Validation\Validation.php(195): CodeIgniter\Validation\Validation->processRules('required', 'required', null, [...], [...])
 3 SYSTEMPATH\Controller.php(150): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\User.php(29): CodeIgniter\Controller->validate('users')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-16 14:16:17 --> syntax error, unexpected token "->", expecting "," or ";"
in APPPATH\Config\Validation.php on line 50.
 1 SYSTEMPATH\Autoloader\Autoloader.php(285): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\teste_api_codeigniter\\app\\Config\\Validation.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(263): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Validation')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Validation')
 4 SYSTEMPATH\Config\Factories.php(277): class_exists('Config\\Validation')
 5 SYSTEMPATH\Config\Factories.php(196): CodeIgniter\Config\Factories::locateClass([...], 'Config\\Validation')
 6 SYSTEMPATH\Config\Factories.php(155): CodeIgniter\Config\Factories::getDefinedInstance([...], 'Config\\Validation', [])
 7 SYSTEMPATH\Common.php(217): CodeIgniter\Config\Factories::__callStatic('config', [])
 8 SYSTEMPATH\Config\Services.php(815): config('Config\\Validation')
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::validation(null, false)
10 SYSTEMPATH\BaseModel.php(332): CodeIgniter\Config\BaseService::__callStatic('validation', [...])
11 SYSTEMPATH\Model.php(155): CodeIgniter\BaseModel->__construct(null)
12 SYSTEMPATH\Config\Factories.php(215): CodeIgniter\Model->__construct(Object(CodeIgniter\Database\Postgre\Connection))
13 SYSTEMPATH\Config\Factories.php(165): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
14 SYSTEMPATH\Common.php(827): CodeIgniter\Config\Factories::__callStatic('models', [...])
15 SYSTEMPATH\RESTful\BaseResource.php(68): model('App\\Models\\UserModel')
16 SYSTEMPATH\RESTful\BaseResource.php(49): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
17 SYSTEMPATH\CodeIgniter.php(892): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
18 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
19 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
20 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
21 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-16 14:22:55 --> Undefined variable $id
in APPPATH\Controllers\User.php on line 41.
 1 APPPATH\Controllers\User.php(41): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $id', 'C:\\teste_api_codeigniter\\app\\Controllers\\User.php', 41)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 17:33:42 --> ErrorException: pg_query(): Query failed: ERROR:  insert or update on table &quot;sales&quot; violates foreign key constraint &quot;sales_users_id_foreign&quot;
DETAIL:  Key (users_id)=(3) is not present in table &quot;users&quot;. in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'INSERT INTO "sa...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "sa...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "sa...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sa...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\teste_api_codeigniter\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#7 C:\teste_api_codeigniter\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(34): CodeIgniter\Model->insert(Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->create()
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 17:33:42 --> pg_query(): Query failed: ERROR:  insert or update on table &quot;sales&quot; violates foreign key constraint &quot;sales_users_id_foreign&quot;
DETAIL:  Key (users_id)=(3) is not present in table &quot;users&quot;.
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO "sales" ("price_amount", "users_id", "products_id", "status", "created_at", "updated_at") VALUES (:price_amount:, :users_id:, :products_id:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Sale.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->create()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-16 17:42:55 --> ErrorException: pg_query(): Query failed: ERROR:  insert or update on table &quot;sales&quot; violates foreign key constraint &quot;sales_users_id_foreign&quot;
DETAIL:  Key (users_id)=(3) is not present in table &quot;users&quot;. in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "sales" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "sales" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "sales" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "sales" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\Sale.php(55): CodeIgniter\Model->update('8', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\Sale->update('8')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-16 17:42:55 --> pg_query(): Query failed: ERROR:  insert or update on table &quot;sales&quot; violates foreign key constraint &quot;sales_users_id_foreign&quot;
DETAIL:  Key (users_id)=(3) is not present in table &quot;users&quot;.
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "sales" SET "price_amount" = :price_amount:, "users_id" = :users_id:, "products_id" = :products_id:, "status" = :status:, "updated_at" = :updated_at:
WHERE "sales"."id" IN :sales.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Sale.php(55): CodeIgniter\Model->update('8', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Sale->update('8')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sale))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
